# Generated by Django 3.2.7 on 2021-09-22 18:09

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('correct_answer', models.PositiveSmallIntegerField(choices=[(None, '---------'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], verbose_name='Correct Answer')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='Last Update Time')),
                ('choice_four', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_choice_four', to='core.choice', verbose_name='Choice Four')),
                ('choice_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_choice_one', to='core.choice', verbose_name='Choice One')),
                ('choice_three', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_choice_three', to='core.choice', verbose_name='Choice Three')),
                ('choice_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_choice_two', to='core.choice', verbose_name='Choice Two')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(verbose_name='Result')),
                ('wrong_count', models.PositiveSmallIntegerField(default=0, verbose_name='Wrong Count')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name='Correct Count')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_exam_exam', to='core.course', verbose_name='Course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_exam_exam', to='core.exam', verbose_name='Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_exam_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exam_questions', to='core.Question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='course',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_exam', to='core.exam', verbose_name='Exam'),
        ),
    ]
